function plot_logl_all(logl_all, recalls, grid)
%PLOT_LOGL_ALL   Visualize recall probabilities generated by a model.
%
%  All probabilities are plotted as a colormap. Each row
%  corresponds to one recall attempt. The first (list length)
%  columns correspond to items on the list. The last column
%  indicates the probability of stopping. Actual recall events are
%  indicated by red dots. If the model is doing a good job, then
%  the red dots should be placed on high-probability recall
%  events. Trials where this is not the case indicate situations
%  where the model could be improved.
%
%  plot_logl_all(logl_all, recalls, grid)
%
%  INPUTS
%  logl_all - [lists x output positions x recall events] numeric array
%      Predicted (log) probability of each possible recall event,
%      according to some model like TCM.
%
%  recalls - [lists x output positions] numeric array
%      Serial position of each actual recall in the experiment.
%
%  grid - [1 x 2] numeric array
%      Size of grid of subplots to make to display all lists. Set
%      to [1 1] to just plot one list.

for i = 1:size(logl_all, 1);
    subplot(grid(1), grid(2), i);
    imagesc(squeeze(logl_all(i,:,:)));
    hold on
    rec = [nonzeros(recalls(i,:))' size(logl_all, 3)];
    plot(rec, 1:length(rec), '.r', 'MarkerFaceColor', 'r');
end
